gs_command:

    display_init_help: '%gs_command.display_init_help%'
    
    #https://raw.githubusercontent.com/sindresorhus/cli-spinners/master/spinners.json
    progress_bar_spin:
    -    ⠋
    -    ⠙
    -    ⠹
    -    ⠸
    -    ⠼
    -    ⠴
    -    ⠦
    -    ⠧
    -    ⠇
    -    ⠏